{
 "title": "Air Quality",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aranet4_connected_to_sensor{aranet4_connected_to_sensor=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hours connected or disconnected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  time()\n-\n  max_over_time(\ntimestamp(changes(aranet4_connected_to_sensor{aranet4_connected_to_sensor=\"true\"}[5m]) > 0)[1d:1m]\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aranet4_battery_level{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "CO2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CO2 Level",
   "type": "timeseries",
   "description": "Shows the level of CO2 over time",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "aranet4_co2{}", "legendFormat": "Home Sensor" }
   ]
  },
  {
   "title": "Current CO2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aranet4_co2{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average CO2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((aranet4_co2 > 0)[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Shows the temperature over time",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "(aranet4_temperature{} * 9/5) + 32",
     "legendFormat": "Home Sensor"
    }
   ]
  },
  {
   "title": "Current Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($Temp * 9/5) + 32", "type": "math" }
   ]
  },
  {
   "title": "Average Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($Temp * 9/5) + 32", "type": "math" }
   ]
  },
  { "title": "Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "Shows the humidity over time",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "aranet4_humidity{}", "legendFormat": "Home Sensor" }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aranet4_humidity{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time((aranet4_humidity > 0)[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}